### ISSUE TITLE
.set_wrapper() and .reset_wrapper() functions are not reachable

### ISSUE THREAD

**Issue by ElmarNeudam** [mshiltonj/resource-routing#5]
.set_wrapper() and .reset_wrapper() functions are not reachable.

In the file 'lib/resource-routing.js' on lines 330 and 331 the private functions are put inside 'this'. But that's inside the .expose_routing_table() function. If I move those two lines outside the .expose_routing_table() function and put directly in the resource_routing() function then the problem is solved.

**Comment by mshiltonj** [comment]
Closing this issue. The package has been rewritten and the wrapper function has been removed.  I expect using express middleware can be used to address any "wrapping" needs. If not, let me now what the use case is. Thanks.
